package com.jiandanjiuer.crm.settings.mapper.dictype;

import com.jiandanjiuer.crm.settings.domain.DicType;

import java.util.List;

/**
 * 数据字典mapper层
 *
 * @author 24245
 */
public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int updateByPrimaryKey(DicType record);

    /**
     * 查询所有的数据字典数据
     *
     * @return
     */
    List<DicType> selectAllDicTypes();

    /**
     * 按照code查询
     *
     * @param code
     * @return
     */
    DicType selectDicTypeByCode(String code);

    /**
     * 保存创建的数据字典
     *
     * @param dicType
     * @return
     */
    int insertDicType(DicType dicType);

    /**
     * 根据codes删除数据
     *
     * @param code
     * @return
     */
    int deleteDicTypeByCodes(String[] code);

    /**
     * 修改数据字典
     *
     * @param dicType
     * @return
     */
    int updateDicType(DicType dicType);
}