package com.jiandanjiuer.crm.settings.mapper;

import com.jiandanjiuer.crm.settings.domain.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Fri Aug 07 19:52:34 CST 2020
     */
    int updateByPrimaryKey(DicType record);

    /**
     * 查询所有的数据字典数据
     * @return
     */
    List<DicType> selectAllDicTypes();
}