package com.jiandanjiuer.crm.workbench.domain.activity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * Activity实体类
 *
 * @author 24245
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Activity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.id
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.owner
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.name
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.start_date
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.end_date
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.cost
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.description
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.create_time
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.create_by
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.edit_time
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.edit_by
     *
     * @mbggenerated Mon Aug 17 09:49:36 CST 2020
     */
    private String editBy;
}